// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bangazon_New.Migrations
{
    [DbContext(typeof(BangazonDbContext))]
    [Migration("20250313202604_AddCarttoUser")]
    partial class AddCarttoUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bangazon.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserPaymentMethodId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Bangazon.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Bangazon.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserPaymentMethodId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserPaymentMethodId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = "6Na5niFGCaUfZz7y9cjbFEq8twj1",
                            IsComplete = false,
                            OrderDate = new DateTime(2025, 3, 13, 20, 26, 4, 610, DateTimeKind.Utc).AddTicks(2340),
                            UserPaymentMethodId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = "6Na5niFGCaUfZz7y9cjbFEq8twj1",
                            IsComplete = true,
                            OrderDate = new DateTime(2025, 3, 5, 20, 26, 4, 610, DateTimeKind.Utc).AddTicks(2340),
                            UserPaymentMethodId = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = "6Na5niFGCaUfZz7y9cjbFEq8twj1",
                            IsComplete = true,
                            OrderDate = new DateTime(2025, 2, 21, 20, 26, 4, 610, DateTimeKind.Utc).AddTicks(2340),
                            UserPaymentMethodId = 3
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = "l4XlJweAr3USaFL4DW3h2PfIqAC3",
                            IsComplete = false,
                            OrderDate = new DateTime(2025, 3, 13, 20, 26, 4, 610, DateTimeKind.Utc).AddTicks(2350),
                            UserPaymentMethodId = 4
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = "l4XlJweAr3USaFL4DW3h2PfIqAC3",
                            IsComplete = true,
                            OrderDate = new DateTime(2025, 3, 1, 20, 26, 4, 610, DateTimeKind.Utc).AddTicks(2350),
                            UserPaymentMethodId = 5
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = "l4XlJweAr3USaFL4DW3h2PfIqAC3",
                            IsComplete = true,
                            OrderDate = new DateTime(2025, 2, 16, 20, 26, 4, 610, DateTimeKind.Utc).AddTicks(2350),
                            UserPaymentMethodId = 6
                        });
                });

            modelBuilder.Entity("Bangazon.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 12,
                            Quantity = 2,
                            SellerId = "l4XlJweAr3USaFL4DW3h2PfIqAC31"
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 21,
                            Quantity = 1,
                            SellerId = "9a53d726-a2cd-42df-9d0f-5ae1a45c1c75"
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 33,
                            Quantity = 3,
                            SellerId = "fa80e4a1-53b7-4784-ab59-6574dea65bb0"
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 45,
                            Quantity = 2,
                            SellerId = "2fe66f47-afdb-4a83-9dff-2d8e60b51b7a"
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 3,
                            ProductId = 39,
                            Quantity = 1,
                            SellerId = "fa80e4a1-53b7-4784-ab59-6574dea65bb0"
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 3,
                            ProductId = 50,
                            Quantity = 2,
                            SellerId = "2fe66f47-afdb-4a83-9dff-2d8e60b51b7a"
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 4,
                            ProductId = 24,
                            Quantity = 2,
                            SellerId = "9a53d726-a2cd-42df-9d0f-5ae1a45c1c75"
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 4,
                            ProductId = 34,
                            Quantity = 1,
                            SellerId = "fa80e4a1-53b7-4784-ab59-6574dea65bb0"
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 5,
                            ProductId = 41,
                            Quantity = 3,
                            SellerId = "2fe66f47-afdb-4a83-9dff-2d8e60b51b7a"
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 5,
                            ProductId = 48,
                            Quantity = 2,
                            SellerId = "2fe66f47-afdb-4a83-9dff-2d8e60b51b7a"
                        },
                        new
                        {
                            Id = 11,
                            OrderId = 6,
                            ProductId = 28,
                            Quantity = 1,
                            SellerId = "9a53d726-a2cd-42df-9d0f-5ae1a45c1c75"
                        },
                        new
                        {
                            Id = 12,
                            OrderId = 6,
                            ProductId = 32,
                            Quantity = 2,
                            SellerId = "fa80e4a1-53b7-4784-ab59-6574dea65bb0"
                        });
                });

            modelBuilder.Entity("Bangazon.Models.PaymentOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PaymentOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Credit Card"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Apple Pay"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Google Pay"
                        },
                        new
                        {
                            Id = 4,
                            Type = "PayPal"
                        });
                });

            modelBuilder.Entity("Bangazon.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Fleetwood Mac's best-selling album.",
                            Image = "https://m.media-amazon.com/images/I/71WxpWovLTL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Rumours",
                            Price = 47.36m,
                            Quantity = 5,
                            SellerId = "6Na5niFGCaUfZz7y9cjbFEq8twj1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Classic Pink Floyd album.",
                            Image = "https://m.media-amazon.com/images/I/81j3Su+bWjL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Dark Side of the Moon",
                            Price = 51.99m,
                            Quantity = 3,
                            SellerId = "6Na5niFGCaUfZz7y9cjbFEq8twj1"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "The Beatles' famous album.",
                            Image = "https://m.media-amazon.com/images/I/81Sl5vNuxBL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Abbey Road",
                            Price = 38.50m,
                            Quantity = 7,
                            SellerId = "6Na5niFGCaUfZz7y9cjbFEq8twj1"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Alanis Morissette's breakthrough album.",
                            Image = "https://m.media-amazon.com/images/I/71+WumJptUL._SL1400_.jpg",
                            IsAvailable = true,
                            Name = "Jagged Little Pill",
                            Price = 15.99m,
                            Quantity = 4,
                            SellerId = "6Na5niFGCaUfZz7y9cjbFEq8twj1"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Nirvana's best-known record.",
                            Image = "https://m.media-amazon.com/images/I/71NRSUUMZXL._SL1400_.jpg",
                            IsAvailable = true,
                            Name = "Nevermind",
                            Price = 29.99m,
                            Quantity = 6,
                            SellerId = "6Na5niFGCaUfZz7y9cjbFEq8twj1"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Adele's Grammy-winning album.",
                            Image = "https://m.media-amazon.com/images/I/71d3FbEovhL._SL1400_.jpg",
                            IsAvailable = true,
                            Name = "21",
                            Price = 19.99m,
                            Quantity = 3,
                            SellerId = "6Na5niFGCaUfZz7y9cjbFEq8twj1"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Lady Gaga's iconic album.",
                            Image = "https://m.media-amazon.com/images/I/91m3bJ6geTL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Born This Way",
                            Price = 22.99m,
                            Quantity = 2,
                            SellerId = "6Na5niFGCaUfZz7y9cjbFEq8twj1"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Michael Jackson's best-selling album.",
                            Image = "https://m.media-amazon.com/images/I/81WcnNQ-TBL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Thriller",
                            Price = 45.00m,
                            Quantity = 9,
                            SellerId = "6Na5niFGCaUfZz7y9cjbFEq8twj1"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Pink Floyd's rock opera.",
                            Image = "https://m.media-amazon.com/images/I/71OQVoZt3ML._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "The Wall",
                            Price = 50.00m,
                            Quantity = 4,
                            SellerId = "6Na5niFGCaUfZz7y9cjbFEq8twj1"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "AC/DC's legendary album.",
                            Image = "https://m.media-amazon.com/images/I/61wq4+PxvFL._SL1400_.jpg",
                            IsAvailable = true,
                            Name = "Back in Black",
                            Price = 39.99m,
                            Quantity = 8,
                            SellerId = "6Na5niFGCaUfZz7y9cjbFEq8twj1"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Taylor Swift's 2019 album with pop anthems.",
                            Image = "https://m.media-amazon.com/images/I/81zWwCEXKPL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Lover",
                            Price = 39.99m,
                            Quantity = 5,
                            SellerId = "l4XlJweAr3USaFL4DW3h2PfIqAC3"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "Taylor Swift's award-winning album from 2014.",
                            Image = "https://m.media-amazon.com/images/I/71r44eosF8L._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "1989",
                            Price = 42.99m,
                            Quantity = 6,
                            SellerId = "l4XlJweAr3USaFL4DW3h2PfIqAC31"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "Kacey Musgraves' Grammy-winning country album.",
                            Image = "https://m.media-amazon.com/images/I/81g8mMUxsnL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Golden Hour",
                            Price = 35.99m,
                            Quantity = 4,
                            SellerId = "l4XlJweAr3USaFL4DW3h2PfIqAC31"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Description = "Taylor Swift's re-recorded classic country-pop album.",
                            Image = "https://m.media-amazon.com/images/I/81bIVb9zTxL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Fearless (Taylor's Version)",
                            Price = 36.50m,
                            Quantity = 7,
                            SellerId = "l4XlJweAr3USaFL4DW3h2PfIqAC31"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Description = "Taylor Swift's re-recording of her hit album Speak Now.",
                            Image = "https://m.media-amazon.com/images/I/71qNte6mGBL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Speak Now (Taylor's Version)",
                            Price = 45.99m,
                            Quantity = 3,
                            SellerId = "l4XlJweAr3USaFL4DW3h2PfIqAC31"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Description = "Folklore's sister album from Taylor Swift.",
                            Image = "https://m.media-amazon.com/images/I/71JJ0VdEP3L._SL1400_.jpg",
                            IsAvailable = true,
                            Name = "Evermore",
                            Price = 38.00m,
                            Quantity = 6,
                            SellerId = "l4XlJweAr3USaFL4DW3h2PfIqAC31"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            Description = "Taylor Swift's highly anticipated 2022 album.",
                            Image = "https://m.media-amazon.com/images/I/71g2zPSy7cL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Midnights",
                            Price = 39.50m,
                            Quantity = 5,
                            SellerId = "l4XlJweAr3USaFL4DW3h2PfIqAC31"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            Description = "Indie-folk album from Taylor Swift featuring Bon Iver.",
                            Image = "https://m.media-amazon.com/images/I/71A8kMA6lsL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Folklore",
                            Price = 37.99m,
                            Quantity = 4,
                            SellerId = "l4XlJweAr3USaFL4DW3h2PfIqAC31"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Description = "Taylor Swift's dark-pop comeback album.",
                            Image = "https://m.media-amazon.com/images/I/71-H5A-YxjL._SL1400_.jpg",
                            IsAvailable = true,
                            Name = "Reputation",
                            Price = 41.99m,
                            Quantity = 8,
                            SellerId = "l4XlJweAr3USaFL4DW3h2PfIqAC31"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Description = "Taylor Swift's iconic breakup album, re-recorded.",
                            Image = "https://m.media-amazon.com/images/I/61KtbxdHUtL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Red (Taylor's Version)",
                            Price = 49.99m,
                            Quantity = 9,
                            SellerId = "l4XlJweAr3USaFL4DW3h2PfIqAC31"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            Description = "The Doors' legendary debut album featuring 'Light My Fire'.",
                            Image = "https://m.media-amazon.com/images/I/81XwnMK0lnL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "The Doors",
                            Price = 28.99m,
                            Quantity = 6,
                            SellerId = "9a53d726-a2cd-42df-9d0f-5ae1a45c1c75"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            Description = "U2's breakthrough album featuring 'With or Without You'.",
                            Image = "https://m.media-amazon.com/images/I/61Qx3-iADfL._SL1200_.jpg",
                            IsAvailable = true,
                            Name = "The Joshua Tree",
                            Price = 29.99m,
                            Quantity = 6,
                            SellerId = "9a53d726-a2cd-42df-9d0f-5ae1a45c1c75"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            Description = "The Beatles' experimental classic from 1966.",
                            Image = "https://m.media-amazon.com/images/I/71-1XnQy3-L._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Revolver",
                            Price = 31.50m,
                            Quantity = 4,
                            SellerId = "9a53d726-a2cd-42df-9d0f-5ae1a45c1c75"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            Description = "Queen's epic album featuring 'Bohemian Rhapsody'.",
                            Image = "https://m.media-amazon.com/images/I/71sN5JB01cL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "A Night at the Opera",
                            Price = 38.99m,
                            Quantity = 7,
                            SellerId = "9a53d726-a2cd-42df-9d0f-5ae1a45c1c75"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            Description = "Jimi Hendrix's groundbreaking double album.",
                            Image = "https://m.media-amazon.com/images/I/71J07CmmyxL._SL1200_.jpg",
                            IsAvailable = true,
                            Name = "Electric Ladyland",
                            Price = 36.99m,
                            Quantity = 5,
                            SellerId = "9a53d726-a2cd-42df-9d0f-5ae1a45c1c75"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 1,
                            Description = "David Bowie's concept album featuring 'Starman'.",
                            Image = "https://m.media-amazon.com/images/I/81Ox3bH8K9L._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "The Rise and Fall of Ziggy Stardust",
                            Price = 27.99m,
                            Quantity = 6,
                            SellerId = "9a53d726-a2cd-42df-9d0f-5ae1a45c1c75"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            Description = "Dire Straits' biggest album featuring 'Money for Nothing'.",
                            Image = "https://m.media-amazon.com/images/I/71b6M0XLvSL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Brothers in Arms",
                            Price = 32.99m,
                            Quantity = 5,
                            SellerId = "9a53d726-a2cd-42df-9d0f-5ae1a45c1c75"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 1,
                            Description = "Van Morrison’s most celebrated album, featuring 'Into the Mystic'.",
                            Image = "https://m.media-amazon.com/images/I/81Ug7cMZk8L._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Moondance",
                            Price = 31.99m,
                            Quantity = 5,
                            SellerId = "9a53d726-a2cd-42df-9d0f-5ae1a45c1c75"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            Description = "A highly influential album with Andy Warhol's iconic banana cover.",
                            Image = "https://m.media-amazon.com/images/I/81vBx5EmKXL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "The Velvet Underground & Nico",
                            Price = 39.99m,
                            Quantity = 6,
                            SellerId = "9a53d726-a2cd-42df-9d0f-5ae1a45c1c75"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            Description = "Another classic from David Bowie featuring 'Life on Mars?'.",
                            Image = "https://m.media-amazon.com/images/I/81a1DlQF7hL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Hunky Dory",
                            Price = 30.99m,
                            Quantity = 7,
                            SellerId = "9a53d726-a2cd-42df-9d0f-5ae1a45c1c75"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 1,
                            Description = "The Clash's iconic punk rock double album.",
                            Image = "https://m.media-amazon.com/images/I/81AwUyc+KHL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "London Calling",
                            Price = 37.99m,
                            Quantity = 6,
                            SellerId = "fa80e4a1-53b7-4784-ab59-6574dea65bb0"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 1,
                            Description = "Prince's legendary album featuring 'When Doves Cry'.",
                            Image = "https://m.media-amazon.com/images/I/81TlfZbcY+L._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Purple Rain",
                            Price = 33.50m,
                            Quantity = 5,
                            SellerId = "fa80e4a1-53b7-4784-ab59-6574dea65bb0"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 1,
                            Description = "Bruce Springsteen's breakthrough album.",
                            Image = "https://m.media-amazon.com/images/I/91pGDOS2yYL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Born to Run",
                            Price = 28.99m,
                            Quantity = 7,
                            SellerId = "fa80e4a1-53b7-4784-ab59-6574dea65bb0"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 1,
                            Description = "The Beach Boys' classic album that redefined pop music.",
                            Image = "https://m.media-amazon.com/images/I/81ZXxdrUwcL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Pet Sounds",
                            Price = 36.99m,
                            Quantity = 5,
                            SellerId = "fa80e4a1-53b7-4784-ab59-6574dea65bb0"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 1,
                            Description = "Eagles' legendary album featuring the title track.",
                            Image = "https://m.media-amazon.com/images/I/71iCZPH5DqL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Hotel California",
                            Price = 34.99m,
                            Quantity = 4,
                            SellerId = "fa80e4a1-53b7-4784-ab59-6574dea65bb0"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 1,
                            Description = "Carole King's masterpiece featuring 'You've Got a Friend'.",
                            Image = "https://m.media-amazon.com/images/I/91wPiHtmwQL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Tapestry",
                            Price = 27.99m,
                            Quantity = 6,
                            SellerId = "fa80e4a1-53b7-4784-ab59-6574dea65bb0"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 1,
                            Description = "Simon & Garfunkel's classic folk-rock album.",
                            Image = "https://m.media-amazon.com/images/I/81KrqZuxNQL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Bridge Over Troubled Water",
                            Price = 32.99m,
                            Quantity = 5,
                            SellerId = "fa80e4a1-53b7-4784-ab59-6574dea65bb0"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 1,
                            Description = "Curtis Mayfield's groundbreaking soul-funk album.",
                            Image = "https://m.media-amazon.com/images/I/91RCpMFXxQL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Superfly",
                            Price = 31.50m,
                            Quantity = 4,
                            SellerId = "fa80e4a1-53b7-4784-ab59-6574dea65bb0"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 1,
                            Description = "Bob Dylan's deeply personal masterpiece.",
                            Image = "https://m.media-amazon.com/images/I/81DBw5cAzQL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Blood on the Tracks",
                            Price = 35.50m,
                            Quantity = 6,
                            SellerId = "fa80e4a1-53b7-4784-ab59-6574dea65bb0"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 1,
                            Description = "The Beatles' final studio album.",
                            Image = "https://m.media-amazon.com/images/I/71qlM3JjXQL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Let It Be",
                            Price = 30.99m,
                            Quantity = 7,
                            SellerId = "fa80e4a1-53b7-4784-ab59-6574dea65bb0"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 1,
                            Description = "Beastie Boys' genre-defining hip-hop album.",
                            Image = "https://m.media-amazon.com/images/I/91tZCYO2iIL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Licensed to Ill",
                            Price = 27.99m,
                            Quantity = 5,
                            SellerId = "2fe66f47-afdb-4a83-9dff-2d8e60b51b7a"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 1,
                            Description = "The Smiths’ iconic post-punk album.",
                            Image = "https://m.media-amazon.com/images/I/81G7lzC5VLL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "The Queen Is Dead",
                            Price = 34.99m,
                            Quantity = 6,
                            SellerId = "2fe66f47-afdb-4a83-9dff-2d8e60b51b7a"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 1,
                            Description = "Red Hot Chili Peppers’ funk-rock breakthrough.",
                            Image = "https://m.media-amazon.com/images/I/71GywSYBKlL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Blood Sugar Sex Magik",
                            Price = 33.50m,
                            Quantity = 4,
                            SellerId = "2fe66f47-afdb-4a83-9dff-2d8e60b51b7a"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 1,
                            Description = "R.E.M.'s critically acclaimed album.",
                            Image = "https://m.media-amazon.com/images/I/81wUOBjHboL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Automatic for the People",
                            Price = 36.99m,
                            Quantity = 7,
                            SellerId = "2fe66f47-afdb-4a83-9dff-2d8e60b51b7a"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 1,
                            Description = "The Pixies’ alternative rock classic.",
                            Image = "https://m.media-amazon.com/images/I/81s6KZp1ajL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Doolittle",
                            Price = 30.99m,
                            Quantity = 6,
                            SellerId = "2fe66f47-afdb-4a83-9dff-2d8e60b51b7a"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 1,
                            Description = "Patti Smith's influential punk album.",
                            Image = "https://m.media-amazon.com/images/I/81MbMS+FDsL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Horses",
                            Price = 38.99m,
                            Quantity = 5,
                            SellerId = "2fe66f47-afdb-4a83-9dff-2d8e60b51b7a"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 1,
                            Description = "Guns N' Roses' explosive debut album.",
                            Image = "https://m.media-amazon.com/images/I/81pLDAZV4LL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Appetite for Destruction",
                            Price = 29.99m,
                            Quantity = 5,
                            SellerId = "2fe66f47-afdb-4a83-9dff-2d8e60b51b7a"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 1,
                            Description = "Fleetwood Mac’s most celebrated album.",
                            Image = "https://m.media-amazon.com/images/I/81vw+8N6WQL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Rumours",
                            Price = 35.99m,
                            Quantity = 7,
                            SellerId = "2fe66f47-afdb-4a83-9dff-2d8e60b51b7a"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 1,
                            Description = "AC/DC’s best-selling rock album of all time.",
                            Image = "https://m.media-amazon.com/images/I/81zBfuU6+RL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Back in Black",
                            Price = 37.50m,
                            Quantity = 6,
                            SellerId = "2fe66f47-afdb-4a83-9dff-2d8e60b51b7a"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 1,
                            Description = "Metallica’s iconic thrash metal album.",
                            Image = "https://m.media-amazon.com/images/I/91zRVgJavIL._SL1500_.jpg",
                            IsAvailable = true,
                            Name = "Master of Puppets",
                            Price = 33.99m,
                            Quantity = 5,
                            SellerId = "2fe66f47-afdb-4a83-9dff-2d8e60b51b7a"
                        });
                });

            modelBuilder.Entity("Bangazon.Models.User", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uid");

                    b.HasIndex("ProductId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Uid = "6Na5niFGCaUfZz7y9cjbFEq8twj1",
                            Address = "123 Elm Street",
                            City = "Nashville",
                            Email = "rolltiderolldad@gmail.com",
                            FirstName = "Brian",
                            LastName = "Suttles",
                            State = "TN",
                            Zip = "37201"
                        },
                        new
                        {
                            Uid = "l4XlJweAr3USaFL4DW3h2PfIqAC3",
                            Address = "123 Elm Street",
                            City = "Nashville",
                            Email = "suttles95@gmail.com",
                            FirstName = "Dayna",
                            LastName = "Suttles",
                            State = "TN",
                            Zip = "37201"
                        },
                        new
                        {
                            Uid = "9a53d726-a2cd-42df-9d0f-5ae1a45c1c75",
                            Address = "789 Pine Street",
                            City = "Atlanta",
                            Email = "alicej@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            State = "GA",
                            Zip = "30301"
                        },
                        new
                        {
                            Uid = "fa80e4a1-53b7-4784-ab59-6574dea65bb0",
                            Address = "321 Maple Avenue",
                            City = "Charlotte",
                            Email = "bobb@example.com",
                            FirstName = "Bob",
                            LastName = "Brown",
                            State = "NC",
                            Zip = "28202"
                        },
                        new
                        {
                            Uid = "2fe66f47-afdb-4a83-9dff-2d8e60b51b7a",
                            Address = "654 Cedar Road",
                            City = "Louisville",
                            Email = "charliem@example.com",
                            FirstName = "Charlie",
                            LastName = "Miller",
                            State = "KY",
                            Zip = "40202"
                        });
                });

            modelBuilder.Entity("Bangazon.Models.UserPaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PaymentOptionId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PaymentOptionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PaymentOptionId = 1,
                            UserId = "6Na5niFGCaUfZz7y9cjbFEq8twj1"
                        },
                        new
                        {
                            Id = 2,
                            PaymentOptionId = 2,
                            UserId = "6Na5niFGCaUfZz7y9cjbFEq8twj1"
                        },
                        new
                        {
                            Id = 3,
                            PaymentOptionId = 3,
                            UserId = "6Na5niFGCaUfZz7y9cjbFEq8twj1"
                        },
                        new
                        {
                            Id = 4,
                            PaymentOptionId = 1,
                            UserId = "l4XlJweAr3USaFL4DW3h2PfIqAC3"
                        },
                        new
                        {
                            Id = 5,
                            PaymentOptionId = 2,
                            UserId = "l4XlJweAr3USaFL4DW3h2PfIqAC3"
                        },
                        new
                        {
                            Id = 6,
                            PaymentOptionId = 3,
                            UserId = "l4XlJweAr3USaFL4DW3h2PfIqAC3"
                        });
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Vinyl"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Cassette"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Compact Disc"
                        });
                });

            modelBuilder.Entity("Bangazon.Models.Cart", b =>
                {
                    b.HasOne("Bangazon.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Bangazon.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bangazon.Models.CartItem", b =>
                {
                    b.HasOne("Bangazon.Models.Cart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bangazon.Models.Product", "Product")
                        .WithOne("CartItem")
                        .HasForeignKey("Bangazon.Models.CartItem", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Bangazon.Models.Order", b =>
                {
                    b.HasOne("Bangazon.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bangazon.Models.UserPaymentMethod", "UserPaymentMethod")
                        .WithMany()
                        .HasForeignKey("UserPaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserPaymentMethod");
                });

            modelBuilder.Entity("Bangazon.Models.OrderItem", b =>
                {
                    b.HasOne("Bangazon.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bangazon.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Bangazon.Models.Product", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bangazon.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Bangazon.Models.User", b =>
                {
                    b.HasOne("Bangazon.Models.Product", null)
                        .WithMany("Users")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("Bangazon.Models.UserPaymentMethod", b =>
                {
                    b.HasOne("Bangazon.Models.PaymentOption", "PaymentOption")
                        .WithMany("UserPaymentMethods")
                        .HasForeignKey("PaymentOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bangazon.Models.User", "User")
                        .WithMany("UserPaymentMethods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentOption");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bangazon.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Bangazon.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Bangazon.Models.PaymentOption", b =>
                {
                    b.Navigation("UserPaymentMethods");
                });

            modelBuilder.Entity("Bangazon.Models.Product", b =>
                {
                    b.Navigation("CartItem")
                        .IsRequired();

                    b.Navigation("OrderItems");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Bangazon.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserPaymentMethods");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
